name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.12.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  http: ^1.1.0
  flutter_dotenv: ^6.0.0
  provider: ^6.1.1
    

# After:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # Updated to the latest major version

flutter:
  uses-material-design: true
  assets:
    - assets/images/1.jpeg
    - assets/images/2.jpeg
    - assets/images/3.jpeg
    - assets/images/Paris.jpeg

